using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ControleGastos.Api.Migrations
{
    /// <inheritdoc />
    public partial class FixPessoaIdIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
		{
			if (ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
			{
				migrationBuilder.Sql(
					@"ALTER TABLE ""Pessoas""
					  ALTER COLUMN ""Id""
					  ADD GENERATED BY DEFAULT AS IDENTITY;"
				);
			}
		}

		protected override void Down(MigrationBuilder migrationBuilder)
		{
			if (ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
			{
				migrationBuilder.Sql(
					@"ALTER TABLE ""Pessoas""
					  ALTER COLUMN ""Id""
					  DROP IDENTITY IF EXISTS;"
				);
			}
		}
    }
}
