using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ControleGastos.Api.Migrations
{
    /// <inheritdoc />
    public partial class FixIdentityCategoriaTransacao : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
		{
			if (ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
			{
				migrationBuilder.Sql(@"ALTER TABLE ""Categoria"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
				migrationBuilder.Sql(@"ALTER TABLE ""Transacao"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
			}
		}

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
		{
			if (ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
			{
				migrationBuilder.Sql(@"ALTER TABLE ""Categoria"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
				migrationBuilder.Sql(@"ALTER TABLE ""Transacao"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
			}
		}
    }
}
